# -*- coding: utf-8 -*-
"""Tugas_PT SERU_SatriyoWisnu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16I6ESYqSau4qaz2rTAxS2S5hXZymTm_0
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://www.carsome.id/'
res = requests.get(url)
res.content
soup = BeautifulSoup(res.content, 'html.parser')

car= soup.find_all("div", class_="mod-b-card__footer")
len(car)

list_products = []
for cars in car:
    item = dict()
    # Mengambil Data Tahun dan Jenis Mobil
    nama_mobil_baris = cars.find('p').text.replace('\n', '').strip()
    nama_tahun = nama_mobil_baris.split(' ', 1)
    tahun_mobil = nama_tahun[0]
    nama_mobil = nama_tahun[1]
    item['Tahun'] = tahun_mobil
    item['Nama'] = nama_mobil
    # Mengambil Data Harga Mobil
    harga_mobil = cars.find("div", class_="mod-card__price-cash").text.strip().replace('Rp ', '').replace(' (Cash)', '').strip()
    item['Harga'] = harga_mobil
    # Mengambil Data Transmisi Kendaraan
    item['Transmisi'] = cars.find("div", class_="mod-b-card__car-other").find_all('span')[1].text
    # Mengambil Data Kilometer
    item['Kilometer'] = cars.find("div", class_="mod-b-card__car-other").find('span').text
    list_products.append(item)

pd.DataFrame(list_products)

df = pd.DataFrame(list_products)
# Menyimpan DataFrame sebagai file CSV
df.to_csv('data_mobil.csv', index=False)